version: 3.17.0.{build}
configuration: Release
platform: Any CPU
build:
  project: NuGetPackageExplorer.sln
  verbosity: minimal
after_build:
- ps: >-
    choco pack PackageExplorer\NugetPackageExplorer.nuspec --version 3.17

    Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
artifacts:
- path: '**\*.nupkg'
deploy: off
