image: Visual Studio 2017
configuration: Release
platform: Any CPU

skip_commits:
  files:
    - '**/*.md'
    - 'images/**/*.*'

skip_branch_with_pr: true   

before_build:
    - ps: msbuild /t:restore PackageExplorer\PackageExplorer.csproj
    
build:
  project: NuGetPackageExplorer.sln
  verbosity: minimal
after_build:
- ps: |
    $vers = & $env:UserProfile\.nuget\packages\nerdbank.gitversioning\2.0.41\tools\Get-Version.ps1
    $nugetVer = $vers.NuGetPackageVersion
    choco pack PackageExplorer\NugetPackageExplorer.nuspec --version $nugetVer

    msbuild /t:pack .\Types\Types.csproj /p:Configuration=Release /p:PackageOutputPath=$Env:APPVEYOR_BUILD_FOLDER

    # Run this again so the version number in the build shows up based on the root
    $vers = & $env:UserProfile\.nuget\packages\nerdbank.gitversioning\2.0.41\tools\Get-Version.ps1
    Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
artifacts:
- path: '**\NugetPackageExplorer*.nupkg'
- path: '**\*.appxupload'
deploy: off
