trigger:
- master
- rel/*

pr:
- master
- rel/*

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
- job: Build
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      Config_Release:
        ReleaseChannel: Zip
      Config_Store:
        ReleaseChannel: Store
      Config_Nightly:
        ReleaseChannel: Nightly
      Config_Choco:
        ReleaseChannel: Choco

  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.0.100-preview6-012264'

  - task: DotNetCoreCLI@2
    inputs:
      command: custom
      custom: tool
      arguments: install --tool-path . nbgv
    displayName: Install NBGV tool

  - script: nbgv cloud -c -a
    displayName: Set Version

  - powershell: |
      mkdir $(Build.ArtifactStagingDirectory)\$(ReleaseChannel)

      # Set versions

      # Update appxmanifests. These must be done before build.
      [xml]$manifest = Get-Content ".\PackageExplorer.Package\package.appxmanifest"
      $manifest.Package.Identity.Version = "$(GitBuildVersionSimple).0"
      $manifest.Save(".\PackageExplorer.Package\package.appxmanifest")

      [xml]$manifest = Get-Content ".\PackageExplorer.Package.Nightly\package.appxmanifest"
      $manifest.Package.Identity.Version = "$(GitBuildVersionSimple).0"
      $manifest.Save(".\PackageExplorer.Package.Nightly\package.appxmanifest")

      # Update badges
      [xml]$badge = Get-Content ".\Build\ci_badge.svg"
      $badge.svg.g[1].text[2].InnerText = "$(GitBuildVersionSimple).0"
      $badge.svg.g[1].text[3].InnerText = "$(GitBuildVersionSimple).0"
      $badge.Save("$(Build.ArtifactStagingDirectory)\$(ReleaseChannel)\ci_badge.svg")

      [xml]$badge = Get-Content ".\Build\store_badge.svg"
      $badge.svg.g[1].text[2].InnerText = "$(GitBuildVersionSimple).0"
      $badge.svg.g[1].text[3].InnerText = "$(GitBuildVersionSimple).0"
      $badge.Save("$(Build.ArtifactStagingDirectory)\$(ReleaseChannel)\stable_badge.svg")
    displayName: Update manifest and badge versions

  - powershell: |
      # Update App Insights key
      [xml]$doc = Get-Content ".\PackageExplorer\ApplicationInsights.config"
      $doc.ApplicationInsights.InstrumentationKey = "$(AppInsightsKey)"
      $doc.Save(".\PackageExplorer\ApplicationInsights.config")

    displayName: Set AppInsights Config
    env:
      AppInsightsKey: $(AppInsightsKey)
    condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['AppInsightsKey'], '')))

  - task: MSBuild@1
    displayName: Build NuGet Package Explorer for $(ReleaseChannel)
    inputs:
      solution: 'PackageExplorer/NuGetPackageExplorer.csproj'
      msbuildArguments: /restore
      maximumCpuCount: true

  - task: MSBuild@1
    displayName: Build Nightly Package
    inputs:
      solution: PackageExplorer.Package.Nightly/PackageExplorer.Package.Nightly.wapproj
      msbuildArguments: /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)\$(ReleaseChannel)\\"
      maximumCpuCount: true
    condition: and(succeeded(), eq(variables['ReleaseChannel'], 'Nightly'))

  - powershell: |
      # Fix AppInstaller update settings
      # This can be removed once 16.1 is on the agent with package templates
      [xml]$doc = Get-Content "$(Build.ArtifactStagingDirectory)\$(ReleaseChannel)\PackageExplorer.Package.Nightly.appinstaller"
      $doc.AppInstaller.UpdateSettings.OnLaunch.HoursBetweenUpdateChecks = "4"
      $toInsert = $doc.CreateElement("AutomaticBackgroundTask", "http://schemas.microsoft.com/appx/appinstaller/2017/2")
      $doc.AppInstaller.UpdateSettings.AppendChild($toInsert)
      $doc.Save("$(Build.ArtifactStagingDirectory)\$(ReleaseChannel)\PackageExplorer.Package.Nightly.appinstaller")
    displayName: Update AppInstaller settings
    condition: and(succeeded(), eq(variables['ReleaseChannel'], 'Nightly'))

  - task: MSBuild@1
    displayName: Build Store Package
    inputs:
      solution: PackageExplorer.Package/PackageExplorer.Package.wapproj
      msbuildArguments: /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)\$(ReleaseChannel)\\" /p:UapAppxPackageBuildMode=CI
      maximumCpuCount: true
    condition: and(succeeded(), eq(variables['ReleaseChannel'], 'Store'))

  - task: MSBuild@1
    displayName: Publish $(ReleaseChannel)
    inputs:
      solution: 'PackageExplorer/NuGetPackageExplorer.csproj'
      msbuildArguments: /t:publish /p:RuntimeIdentifier=win-x86 /p:SelfContained=true /p:PublishReadyToRun=true
      maximumCpuCount: true
    condition: and(succeeded(), or(eq(variables['ReleaseChannel'], 'Release'), eq(variables['ReleaseChannel'], 'Choco')))

  - task: MSBuild@1
    displayName: Pack Types Package
    inputs:
      solution: Types/Types.csproj
      msbuildArguments: /t:pack /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)\$(ReleaseChannel)\NuGet
      maximumCpuCount: true
    condition: and(succeeded(), eq(variables['ReleaseChannel'], 'Release'))

  - powershell: |
      # Chocolatey
      & choco.exe pack .\PackageExplorer\NuGetPackageExplorer.nuspec --version $(NBGV_ChocolateyPackageVersion) --OutputDirectory $(Build.ArtifactStagingDirectory)\$(ReleaseChannel)
    displayName: Create Choco package
    condition: and(succeeded(), eq(variables['ReleaseChannel'], 'Choco'))

  - task: ArchiveFiles@1
    displayName: Zip PackageExplorer files
    inputs:
      archiveType: zip
      rootFolder: PackageExplorer/bin/$(BuildConfiguration)/netcoreapp3.0/win-x86/publish
      archiveFile: $(Build.ArtifactStagingDirectory)\$(ReleaseChannel)\PackageExplorer.$(Build.BuildNumber).zip
      includeRootFolder: false
    condition: and(succeeded(), eq(variables['ReleaseChannel'], 'Release'))

  - task: DotNetCoreCLI@2
    inputs:
      command: custom
      custom: tool
      arguments: install --tool-path $(System.DefaultWorkingDirectory)\Build SignClient
    displayName: Install SignTool tool
    condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))

  - task: PowerShell@2
    displayName: Authenticode Sign $(ReleaseChannel) Package artifacts
    inputs:
      filePath: Build/Sign-Package.ps1
    env:
      SignClientUser: $(SignClientUser)
      SignClientSecret: $(SignClientSecret)
      ArtifactDirectory: $(Build.ArtifactStagingDirectory)\$(ReleaseChannel)
    condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))

  - task: PowerShell@2
    displayName: Authenticode Sign $(ReleaseChannel) Zip artifacts
    inputs:
      filePath: Build/Sign-Zip.ps1
    env:
      SignClientUser: $(SignClientUser)
      SignClientSecret: $(SignClientSecret)
      ArtifactDirectory: $(Build.ArtifactStagingDirectory)\$(ReleaseChannel)
    condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))

  - task: PublishBuildArtifacts@1
    displayName: Publish $(ReleaseChannel) Artifact
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)\$(ReleaseChannel)
      artifactType: container
      artifactName: $(ReleaseChannel)
